---
title: "ESM 244 Lab 3 part 2: kriging"
author: "Max Pepperdine"
format: 
  html: 
    code-fold: show
    toc: true
    number-sections: true
    embed-resources: true
editor: visual
execute: 
  echo: true
  message: false
  warning: false
---

```{r}
library(tidyverse)
library(here)
library(sf) ### vector spatial data
library(terra) ### raster spatial data
library(tidyterra) ### for rasters in ggplot
library(gstat)
library(stars)
```

# Overview

Create a variogram in R to understand the spatial dependence of ground water depth in CA. 

# Read in the data!

```{r}
ca_counties_sf <- read_sf(here("data/ca_counties"), 
                          layer = "CA_Counties_TIGER2016") %>% 
  janitor::clean_names() %>% 
  select(name)

ca_dgw_sf <- read_sf(here("data/ca_dgw/F2013_DBGS_Points_20150720_093252.gpkg")) %>% 
  janitor::clean_names()
```

cmd + shift + c comments out an entire section
```{r}
# st_crs(ca_counties_sf)
# st_crs(ca_dgw_sf)

ca_dgw_sf <- st_transform(ca_dgw_sf, 3857) %>% 
  rename(depth = dgbs) #rename the dgbs column
```

```{r}
ggplot() +
  geom_sf(data = ca_counties_sf) +
  geom_sf(data = ca_dgw_sf, aes(color = depth))
```

# Focus on San Joaquin County 

```{r}
#take out only SJ County 
sj_county_sf <- ca_counties_sf %>% 
  filter(name == "San Joaquin")

#keep only areas of overlap
sj_depth_sf <- ca_dgw_sf %>% 
  st_intersection(sj_county_sf) 
```

```{r}
ggplot() +
  geom_sf(data = sj_county_sf) +
  geom_sf(data = sj_depth_sf, aes(color = depth)) +
  theme_void()
```

# Spatial interpolation

## Make a variogram

```{r}
#generate a variogram
sj_dgw_vgm <- gstat::variogram(depth ~ 1, data = sj_depth_sf)
plot(sj_dgw_vgm)


#fit a line to the variogram 
vgm_fit <- fit.variogram(sj_dgw_vgm, 
                         model = vgm(model = "Gau", nugget = TRUE))
plot(sj_dgw_vgm, vgm_fit)


#look at attributes in the model 
attr(vgm_fit, "SSErr") 
```

```{r}
sj_grid <- st_bbox(sj_county_sf) %>% #make a grid that fits the desired county
  stars::st_as_stars(dx = 1000, dy = 1000) #put random points every 1000m


#take our variogram model, the data we give it, and predict the depth in areas around it. Predict the depth throughout our defined grid. 
dgw_krige <- krige(depth ~ 1, sj_depth_sf, sj_grid, model = vgm_fit)

plot(dgw_krige)
```

```{r}
krige_rast <- dgw_krige %>% 
  terra::rast() %>% 
  setNames(c("pred", "var"))

#compares predicted values with actual values
ggplot() +
  tidyterra::geom_spatraster(data = krige_rast, aes(fill = pred)) +
  geom_sf(data = sj_depth_sf, aes(fill = depth), shape = 21) +
  geom_sf(data = sj_county_sf, color = "black", fill = NA) +
  scale_fill_gradient(low = "green", high = "blue")

#shows the relative strength of prediction throughout the area
#higher variance --> weaker prediction capacity 
ggplot() +
  tidyterra::geom_spatraster(data = krige_rast, aes(fill = var)) +
  geom_sf(data = sj_depth_sf, aes(fill = depth), shape = 21) +
  geom_sf(data = sj_county_sf, color = "black", fill = NA) +
  scale_fill_gradient(low = "green", high = "blue")
```











